# GitHub Actions Workflow for Automated Releases
# Place this file in: .github/workflows/release.yml

name: Automated Release

on:
  # Trigger on push to main branch
  push:
    branches: [main]
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        required: false
        type: boolean
        default: false

jobs:
  # Job 1: Run tests before releasing
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
        continue-on-error: true
      
      - name: Run tests
        run: npm test
      
      - name: Build project
        run: npm run build
  
  # Job 2: Analyze changes and determine if release is needed
  analyze:
    name: Analyze Changes
    runs-on: ubuntu-latest
    needs: test
    
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
      version: ${{ steps.analyze.outputs.version }}
      bump_type: ${{ steps.analyze.outputs.bump_type }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check for completion documents
        id: check
        run: |
          # Check if there are new completion documents since last release
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            # No previous tags, check for any completion docs
            DOCS=$(find .kiro/specs/*/completion -name '*.md' 2>/dev/null | wc -l)
          else
            # Check for completion docs newer than last tag
            DOCS=$(find .kiro/specs/*/completion -name '*.md' -newer <(git log -1 --format=%ai $LAST_TAG) 2>/dev/null | wc -l)
          fi
          
          if [ "$DOCS" -gt 0 ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "Found $DOCS completion document(s) - release needed"
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "No completion documents found - skipping release"
          fi
      
      - name: Run release analysis
        id: analyze
        if: steps.check.outputs.should_release == 'true'
        run: |
          # Run analysis and capture output
          OUTPUT=$(npm run release:analyze --format json)
          
          # Extract version and bump type
          VERSION=$(echo "$OUTPUT" | jq -r '.recommendedVersion')
          BUMP_TYPE=$(echo "$OUTPUT" | jq -r '.bumpType')
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
          echo "Recommended version: $VERSION (bump: $BUMP_TYPE)"
  
  # Job 3: Execute the release
  release:
    name: Execute Release
    runs-on: ubuntu-latest
    needs: analyze
    if: needs.analyze.outputs.should_release == 'true'
    
    permissions:
      contents: write    # For creating releases and tags
      packages: write    # For publishing packages
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Execute release (dry run)
        if: github.event.inputs.dry_run == 'true'
        run: npm run release:cli release auto --dry-run --skip-confirmation --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Execute release
        if: github.event.inputs.dry_run != 'true'
        run: npm run release:cli release auto --skip-confirmation --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Upload release logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: release-logs
          path: .kiro/logs/
          retention-days: 30
  
  # Job 4: Notify on completion
  notify:
    name: Notify Release Status
    runs-on: ubuntu-latest
    needs: [analyze, release]
    if: always()
    
    steps:
      - name: Notify success
        if: needs.release.result == 'success'
        run: |
          echo "✅ Release successful!"
          echo "Version: ${{ needs.analyze.outputs.version }}"
          echo "Bump type: ${{ needs.analyze.outputs.bump_type }}"
      
      - name: Notify skipped
        if: needs.analyze.outputs.should_release != 'true'
        run: |
          echo "ℹ️ Release skipped - no completion documents found"
      
      - name: Notify failure
        if: needs.release.result == 'failure'
        run: |
          echo "❌ Release failed!"
          echo "Check logs for details"
      
      - name: Create issue on failure
        if: needs.release.result == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Automated release failed',
              body: `The automated release workflow failed.
              
              **Details:**
              - Run: ${context.runId}
              - Commit: ${context.sha}
              - Branch: ${context.ref}
              
              **Action Required:**
              1. Check workflow logs: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
              2. Review release manager logs (uploaded as artifact)
              3. Fix issues and re-run workflow
              
              **Troubleshooting:**
              - Verify GitHub token permissions
              - Verify npm token is valid
              - Check completion documents are properly formatted
              - Review error messages in logs`,
              labels: ['release', 'automation', 'bug']
            })

# Optional: Add a separate workflow for manual releases
# This allows team members to trigger releases manually with more control
---
name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Override version (leave empty for automatic)'
        required: false
        type: string
      skip_tests:
        description: 'Skip tests (not recommended)'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Dry run (preview only)'
        required: false
        type: boolean
        default: false

jobs:
  manual-release:
    name: Manual Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        if: github.event.inputs.skip_tests != 'true'
        run: npm test
      
      - name: Build project
        run: npm run build
      
      - name: Execute release
        run: |
          if [ -n "${{ github.event.inputs.version_override }}" ]; then
            npm run release:cli release manual --version ${{ github.event.inputs.version_override }} --skip-confirmation
          elif [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            npm run release:cli release auto --dry-run --skip-confirmation
          else
            npm run release:cli release auto --skip-confirmation
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
